// UAFSAIDA — Project Export System
// Exports generated applications for external development

import { GeneratedCode, ProjectFile } from '@/types';
import { createWriteStream } from 'fs';
import { mkdir, writeFile } from 'fs/promises';
import { join } from 'path';
import { tmpdir } from 'os';

export class ProjectExportEngine {
  /**
   * Export a project to a local directory
   */
  async exportToDirectory(
    projectId: string,
    files: GeneratedFile[],
    targetPath: string
  ): Promise<ExportResult> {
    try {
      // Create target directory
      await mkdir(targetPath, { recursive: true });

      // Write all files
      for (const file of files) {
        const filePath = join(targetPath, file.path);
        const dirPath = join(targetPath, file.path.split('/').slice(0, -1).join('/'));
        
        await mkdir(dirPath, { recursive: true });
        await writeFile(filePath, file.content, 'utf-8');
      }

      return {
        success: true,
        projectId,
        path: targetPath,
        filesExported: files.length,
        message: `Project exported to ${targetPath}`,
      };
    } catch (error) {
      return {
        success: false,
        projectId,
        path: targetPath,
        filesExported: 0,
        message: `Export failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
      };
    }
  }

  /**
   * Generate a complete project package
   */
  async generatePackage(
    projectId: string,
    files: GeneratedFile[],
    options: ExportOptions
  ): Promise<ExportResult> {
    const exportPath = options.outputPath || join(tmpdir(), `uafsaida-${projectId}`);
    
    // Export files
    const result = await this.exportToDirectory(projectId, files, exportPath);
    
    if (!result.success) {
      return result;
    }

    // Generate documentation
    if (options.includeDocumentation) {
      await this.generateDocumentation(files, exportPath);
    }

    // Generate setup script
    if (options.includeSetupScript) {
      await this.generateSetupScript(exportPath);
    }

    // Generate environment template
    if (options.includeEnvTemplate) {
      await this.generateEnvTemplate(exportPath);
    }

    return {
      ...result,
      filesExported: result.filesExported + 3,
      message: `Package generated at ${exportPath}`,
    };
  }

  private async generateDocumentation(files: GeneratedFile[], basePath: string): Promise<void> {
    const readme = this.generateReadme(files);
    await writeFile(join(basePath, 'README.md'), readme, 'utf-8');
  }

  private generateReadme(files: GeneratedFile[]): string {
    return `# Generated Project

## Overview
This project was generated by UAFSAIDA - Universal AI Software Development Platform.

## Files
${files.map(f => `- \`${f.path}\` - ${f.description}`).join('\n')}

## Setup
1. Install dependencies: \`npm install\`
2. Copy \`.env.example\` to \`.env.local\`
3. Run the development server: \`npm run dev\`

## License
MIT
`;
  }

  private async generateSetupScript(basePath: string): Promise<void> {
    const script = `#!/bin/bash
echo "Setting up the project..."
npm install
cp .env.example .env.local
echo "Setup complete! Run 'npm run dev' to start the development server."
`;
    await writeFile(join(basePath, 'setup.sh'), script, 'utf-8');
  }

  private async generateEnvTemplate(basePath: string): Promise<void> {
    const template = `# Database
DATABASE_URL="postgresql://user:password@localhost:5432/mydb"

# NextAuth
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="change-me-to-a-random-secret"

# OAuth (optional)
GITHUB_CLIENT_ID=""
GITHUB_CLIENT_SECRET=""
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""

# API Keys
ANTHROPIC_API_KEY=""
`;
    await writeFile(join(basePath, '.env.example'), template, 'utf-8');
  }
}

export interface ExportOptions {
  outputPath?: string;
  includeDocumentation: boolean;
  includeSetupScript: boolean;
  includeEnvTemplate: boolean;
}

export interface ExportResult {
  success: boolean;
  projectId: string;
  path: string;
  filesExported: number;
  message: string;
}

export interface GeneratedFile {
  path: string;
  content: string;
  language: string;
  description: string;
  isTest: boolean;
  isConfig: boolean;
}
